# Generated by Codex on 2026-06-13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def populate_required_permit_references(apps, schema_editor):
    WorkArea = apps.get_model("permits", "WorkArea")
    WorkType = apps.get_model("permits", "WorkType")
    Permit = apps.get_model("permits", "Permit")

    default_area, _ = WorkArea.objects.get_or_create(
        name="Default work area",
        defaults={"description": "Default work area for existing permits."},
    )
    default_type, _ = WorkType.objects.get_or_create(
        name="Default work type",
        defaults={"description": "Default work type for existing permits."},
    )

    Permit.objects.filter(work_area__isnull=True).update(work_area=default_area)
    Permit.objects.filter(work_type__isnull=True).update(work_type=default_type)


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0002_equipment_hazard_safetymeasure_workarea_worktype_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipment",
            old_name="inventory_number",
            new_name="code",
        ),
        migrations.RemoveConstraint(
            model_name="equipment",
            name="unique_equipment_inventory_per_work_area",
        ),
        migrations.AddField(
            model_name="workarea",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workarea",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workarea",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equipment",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equipment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equipment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="worktype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="worktype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hazard",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hazard",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="safetymeasure",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="safetymeasure",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="equipment",
            options={"ordering": ["name", "code"]},
        ),
        migrations.AddConstraint(
            model_name="equipment",
            constraint=models.UniqueConstraint(
                fields=("work_area", "code"),
                name="unique_equipment_code_per_work_area",
            ),
        ),
        migrations.RunPython(populate_required_permit_references, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="permit",
            name="work_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="permits",
                to="permits.workarea",
            ),
        ),
        migrations.AlterField(
            model_name="permit",
            name="work_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="permits",
                to="permits.worktype",
            ),
        ),
    ]
