# Generated by Django 5.2.15 on 2026-06-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0003_reference_directories_metadata_and_required_permit_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="permit",
            name="additional_conditions",
            field=models.TextField(blank=True, verbose_name="additional conditions"),
        ),
        migrations.AddField(
            model_name="permit",
            name="additional_safety_notes",
            field=models.TextField(blank=True, verbose_name="additional safety notes"),
        ),
        migrations.AddField(
            model_name="permit",
            name="responsible_manager_text",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="responsible manager free-text value",
            ),
        ),
        migrations.AddField(
            model_name="permit",
            name="work_nature_text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="work nature free-text value"
            ),
        ),
        migrations.AddField(
            model_name="permit",
            name="work_producer_text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="work producer free-text value"
            ),
        ),
    ]
