# Generated by Django 5.2.15 on 2026-06-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0005_personnelgroup_personnel_permitparticipant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={
                "ordering": ["name", "code"],
                "verbose_name": "Оборудование",
                "verbose_name_plural": "Оборудование",
            },
        ),
        migrations.AlterModelOptions(
            name="hazard",
            options={
                "ordering": ["name"],
                "verbose_name": "Опасность",
                "verbose_name_plural": "Опасности",
            },
        ),
        migrations.AlterModelOptions(
            name="permit",
            options={
                "ordering": ["-created_at", "number"],
                "verbose_name": "Наряд-допуск",
                "verbose_name_plural": "Наряды-допуски",
            },
        ),
        migrations.AlterModelOptions(
            name="permitparticipant",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "Участник наряда",
                "verbose_name_plural": "Участники наряда",
            },
        ),
        migrations.AlterModelOptions(
            name="personnel",
            options={
                "ordering": ["full_name", "personnel_number"],
                "verbose_name": "Работник",
                "verbose_name_plural": "Персонал",
            },
        ),
        migrations.AlterModelOptions(
            name="personnelgroup",
            options={
                "ordering": ["name"],
                "verbose_name": "Группа персонала",
                "verbose_name_plural": "Группы персонала",
            },
        ),
        migrations.AlterModelOptions(
            name="safetymeasure",
            options={
                "ordering": ["name"],
                "verbose_name": "Мера безопасности",
                "verbose_name_plural": "Меры безопасности",
            },
        ),
        migrations.AlterModelOptions(
            name="workarea",
            options={
                "ordering": ["name"],
                "verbose_name": "Участок",
                "verbose_name_plural": "Участки",
            },
        ),
        migrations.AlterModelOptions(
            name="worktype",
            options={
                "ordering": ["name"],
                "verbose_name": "Вид работ",
                "verbose_name_plural": "Виды работ",
            },
        ),
        migrations.AlterField(
            model_name="equipment",
            name="code",
            field=models.CharField(max_length=128, verbose_name="Код"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="hazard",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="hazard",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="hazard",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="hazard",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="hazard",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="permit",
            name="additional_conditions",
            field=models.TextField(blank=True, verbose_name="Дополнительные условия"),
        ),
        migrations.AlterField(
            model_name="permit",
            name="additional_safety_notes",
            field=models.TextField(
                blank=True, verbose_name="Дополнительные меры безопасности"
            ),
        ),
        migrations.AlterField(
            model_name="permit",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="permit",
            name="number",
            field=models.CharField(max_length=64, unique=True, verbose_name="Номер"),
        ),
        migrations.AlterField(
            model_name="permit",
            name="responsible_manager_text",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Ответственный руководитель работ (ручной ввод)",
            ),
        ),
        migrations.AlterField(
            model_name="permit",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("submitted", "Отправлен мастеру"),
                    ("returned", "Возвращён на доработку"),
                    ("approved_by_master", "Согласован мастером"),
                    ("approved_by_chief", "Утверждён начальником"),
                    ("rejected", "Отклонён"),
                    ("closed", "Закрыт"),
                    ("archived", "В архиве"),
                ],
                default="draft",
                max_length=32,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="permit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="permit",
            name="work_description",
            field=models.TextField(verbose_name="Описание работ"),
        ),
        migrations.AlterField(
            model_name="permit",
            name="work_ends_at",
            field=models.DateTimeField(verbose_name="Окончание работ"),
        ),
        migrations.AlterField(
            model_name="permit",
            name="work_location",
            field=models.CharField(max_length=255, verbose_name="Место работ"),
        ),
        migrations.AlterField(
            model_name="permit",
            name="work_nature_text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Характер работ"
            ),
        ),
        migrations.AlterField(
            model_name="permit",
            name="work_producer_text",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Производитель работ (ручной ввод)",
            ),
        ),
        migrations.AlterField(
            model_name="permit",
            name="work_starts_at",
            field=models.DateTimeField(verbose_name="Начало работ"),
        ),
        migrations.AlterField(
            model_name="permitparticipant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="permitparticipant",
            name="manual_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Ручной ввод участника"
            ),
        ),
        migrations.AlterField(
            model_name="permitparticipant",
            name="note",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Примечание"
            ),
        ),
        migrations.AlterField(
            model_name="permitparticipant",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AlterField(
            model_name="permitparticipant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="department",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Подразделение"
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Примечания"),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="personnel_number",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Табельный номер"
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="phone",
            field=models.CharField(blank=True, max_length=64, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="position",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Должность"
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="personnelgroup",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="personnelgroup",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="personnelgroup",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="personnelgroup",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="personnelgroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="safetymeasure",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="safetymeasure",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="safetymeasure",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="safetymeasure",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="safetymeasure",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="workarea",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="workarea",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="workarea",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="workarea",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="workarea",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
    ]
