# Generated by Django 5.2.15 on 2026-06-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documenttemplate",
            options={
                "ordering": ["document_type", "-created_at"],
                "verbose_name": "DOCX-шаблон",
                "verbose_name_plural": "DOCX-шаблоны",
            },
        ),
        migrations.AlterModelOptions(
            name="generateddocument",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Сформированный документ",
                "verbose_name_plural": "Сформированные документы",
            },
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="document_type",
            field=models.CharField(max_length=64, verbose_name="Тип документа"),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="file",
            field=models.FileField(
                upload_to="document_templates/", verbose_name="Файл DOCX-шаблона"
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="version",
            field=models.CharField(max_length=32, verbose_name="Версия"),
        ),
        migrations.AlterField(
            model_name="generateddocument",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="generateddocument",
            name="file_docx",
            field=models.FileField(
                upload_to="generated_documents/docx/", verbose_name="Файл DOCX"
            ),
        ),
        migrations.AlterField(
            model_name="generateddocument",
            name="file_pdf",
            field=models.FileField(
                blank=True,
                upload_to="generated_documents/pdf/",
                verbose_name="Файл PDF",
            ),
        ),
    ]
