# Generated by Django 5.2.15 on 2026-06-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Запись аудита",
                "verbose_name_plural": "Журнал аудита",
            },
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(max_length=128, verbose_name="Действие"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="details",
            field=models.JSONField(blank=True, default=dict, verbose_name="Детали"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.CharField(max_length=128, verbose_name="ID объекта"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_type",
            field=models.CharField(max_length=128, verbose_name="Тип объекта"),
        ),
    ]
