# Generated by Django 5.2.15 on 2026-06-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approvalaction",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Действие согласования",
                "verbose_name_plural": "Действия согласования",
            },
        ),
        migrations.AlterField(
            model_name="approvalaction",
            name="action",
            field=models.CharField(max_length=64, verbose_name="Действие"),
        ),
        migrations.AlterField(
            model_name="approvalaction",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="approvalaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="approvalaction",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("submitted", "Отправлен мастеру"),
                    ("returned", "Возвращён на доработку"),
                    ("approved_by_master", "Согласован мастером"),
                    ("approved_by_chief", "Утверждён начальником"),
                    ("rejected", "Отклонён"),
                    ("closed", "Закрыт"),
                    ("archived", "В архиве"),
                ],
                max_length=32,
                verbose_name="Новый статус",
            ),
        ),
        migrations.AlterField(
            model_name="approvalaction",
            name="old_status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("submitted", "Отправлен мастеру"),
                    ("returned", "Возвращён на доработку"),
                    ("approved_by_master", "Согласован мастером"),
                    ("approved_by_chief", "Утверждён начальником"),
                    ("rejected", "Отклонён"),
                    ("closed", "Закрыт"),
                    ("archived", "В архиве"),
                ],
                max_length=32,
                verbose_name="Старый статус",
            ),
        ),
    ]
